# Logging configuration
logging:
  level: INFO # Logging level

# Energy
E2NodeList:
  - mcc: 310
    mnc: 260
    nodebid: 10001
    radioPower: 18.5
  - mcc: 311
    mnc: 480
    nodebid: 10002
    radioPower: 22.0


# Configuration for O1 comunications
O1:
  E2Nodes:
    - '72411_00000001': 'http://e2node1-e2sim-helm-o1.ricplt:8090/restconf/operations/tx-gain'
    - '72411_00000002': 'http://e2node2-e2sim-helm-o1.ricplt:8090/restconf/operations/tx-gain'
    - '72411_00000003': 'http://e2node3-e2sim-helm-o1.ricplt:8090/restconf/operations/tx-gain'
    - '72411_00000004': 'http://e2node4-e2sim-helm-o1.ricplt:8090/restconf/operations/tx-gain'

# Configuration settings for the energy-saver-rapp application trigger
# Just one can be enabled at the same time
trigger:
  # The interval in seconds at which the trigger should occur. Set to 0 to disable the trigger.
  interval:
    enable: False
    seconds: 10
  # User variation configuration
  user_variation:
    enable: True
    # The percentage of the user variation. Should be between 0 and 1.
    percentage: 0.2
    # Minimum time since the last run in seconds
    min_time_since_last_run_seconds: 10

# Non-RT RIC configuration
nonrtric:
  base_url_rApp_catalogue: 'http://rappcatalogueservice.nonrtric.svc.cluster.local:9085/services'
  base_url_pms: 'http://nonrtricgateway.nonrtric.svc.cluster.local:9090/a1-policy/v2'
  service_name: 'rAppEnergySaver'
  service_version: 'v1'
  service_display_name: 'rApp Energy Saver'
  service_description: 'Energy-saving application for optimizing power consumption of E2Nodes'
  ric_id: 'ric4'
  radiopower_policytype_id: '4'

# Kafka configuration
kafka:
  bootstrap_servers: "kafka.smo.svc.cluster.local" # Kafka host
  port: 9092 # Kafka port number
  enable_auto_commit: True
  auto_commit_interval_ms: 6000
  auto_offset_reset: "latest"
  group_id: "rAppEnergySaver"
  client_id: "rAppEnergySaver"
  poll_timeout_seconds: 1
  topics:
  - ues